version: "3.9"
services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node API service
  #Changed ports from 3000:3000 to 8080:3000
  api:
    build: .
    expose:
      - "3000" # Open the port to other Docker containers
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: idk
    depends_on:
      - mongo_db
    volumes:
      - ./uploads/:/usr/src/app/uploads

volumes:
  mongo_db: {}
